[package]
name = "a4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
chashmap = "2.2"
num-bigint = "~0.4"
bitvec = "~1.0.0"
